security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        # password = admin123
                        password: "$2y$13$ipmCJAzt6yo9xmGQcVmek.7zmSuuSaxiu/Yh3EuHu47I2gFk0Xl7C"
                        roles: ["ROLE_ADMIN"]
                    user:
                        # password = user123
                        password: "$2y$13$q8SzansSj5UrYCNXsRKMT.KXN4hbC3T6AO8hfey8AmQ5nSttKmGji"
                        roles: ["ROLE_USER"]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            http_basic: ~

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }